# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_test

  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftOverlays', '~> 5.0.1'
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'

  target 'ios_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
